<a href="https://colab.research.google.com/github/VinayChavan2006/EE655-Computer-Vision-and-Deep-Learning/blob/main/Pytorch_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch Problems

### Level 1

#### Problem 1
##### Tensor Basics:

- Create a random tensor of size (5, 3).
- Perform element-wise addition, subtraction, multiplication, and division between two tensors of the same size.
- Calculate the mean and standard deviation of a tensor.
- Reshape a tensor from (4, 4) to (16,) and then back to (2, 8).
- Convert a NumPy array to a PyTorch tensor and vice versa.

In [33]:
import torch
import numpy as np

# create random tensor of size (5,3)
tensor1 = torch.rand(5,3)
print(tensor1)
print("\n\n")

# some more tensors
t_ones = torch.ones(4,3)
t_zeros = torch.zeros(3,3)
t_range = torch.arange(10,dtype=torch.float32)
t_lin = torch.linspace(1,10,3)

tensors = [t_ones,t_zeros,t_range,t_lin]
for tensor in tensors:
  print(tensor)
  print(tensor.dtype,tensor.shape,tensor.dim)
  print("\n\n")

# Element wise operations
t1 = torch.randint(0,20,(3,4))
t2 = torch.randint(0,25,(3,4))

print(t1)
print(t2)
print(t1+t2)
print("\n\n")
print(t1 - t2)
print("\n\n")
print(t1 * t2)
print("\n\n")
print(torch.div(t1,t2))

# mean and std of a tensor
ten1 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print("mean",ten1.mean())
print("median: ",ten1.median())
print("std: ",ten1.std())


# reshape_tensor
re_ten = torch.randint(0,10,(4,4))
print(re_ten)
print(re_ten.view(16))
print(re_ten.view(-1,8))

# covert a numpy array in to torch tensor and vice versa
np_arr = np.array([[100,200,300],[120,240,360],[200,300,400]])
np_tens = torch.Tensor(np_arr)
print(np_tens)

tens_arr = torch.randn(3,3)
tens_np = np.array(tens_arr)
print(tens_np)


tensor([[0.9220, 0.5208, 0.1907],
        [0.0296, 0.9795, 0.7871],
        [0.2717, 0.1918, 0.3912],
        [0.6184, 0.0376, 0.8007],
        [0.6676, 0.3438, 0.6600]])



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32 torch.Size([4, 3]) <built-in method dim of Tensor object at 0x7d253c547350>



tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32 torch.Size([3, 3]) <built-in method dim of Tensor object at 0x7d253c546d50>



tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32 torch.Size([10]) <built-in method dim of Tensor object at 0x7d253c690110>



tensor([ 1.0000,  5.5000, 10.0000])
torch.float32 torch.Size([3]) <built-in method dim of Tensor object at 0x7d25692fac90>



tensor([[ 3, 12, 16,  8],
        [16, 11,  6,  4],
        [ 6, 12,  6,  3]])
tensor([[20,  8,  6, 11],
        [11, 12, 21, 16],
        [ 7,  6, 24,  2]])
tensor([[23, 20, 22, 19],
        [27, 23, 27, 20],
        

#### Problem 2
##### Simple Linear Regression:
-
Implement linear regression from scratch using PyTorch. Generate some synthetic data (e.g., y = 2x + 1 + noise).
- Define a simple linear model with one input and one output.
- Use torch.nn.MSELoss as the loss function and torch.optim.SGD for optimization.
- Train the model for a few epochs and observe the loss decreasing.

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim

class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)
  def forward(self,X):
    return self.linear(X)

X = torch.rand(1000,1,dtype=torch.float32)
y = 2*X + 1 + torch.randn(1000,1,dtype=torch.float32)
X_train = X[:800]
y_train = y[:800]
X_test = X[800:]
y_test = y[800:]

model = LinearRegression()
loss_func = nn.MSELoss()
optimiser = torch.optim.SGD(model.parameters(),lr=0.1)

epochs = 300
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train)

  # loss calc
  loss = loss_func(y_pred,y_train)

  # back propagate
  loss.backward()

  # update weights
  optimiser.step()

  # zero the grads
  optimiser.zero_grad()

  if epoch % 5 == 0:
    print(f"Epoch: {epoch}, Loss: {loss.item()} model params = {model.linear.weight}")

Epoch: 0, Loss: 4.2718095779418945 model params = Parameter containing:
tensor([[0.6129]], requires_grad=True)
Epoch: 5, Loss: 1.3074816465377808 model params = Parameter containing:
tensor([[1.0908]], requires_grad=True)
Epoch: 10, Loss: 1.1343876123428345 model params = Parameter containing:
tensor([[1.2450]], requires_grad=True)
Epoch: 15, Loss: 1.1182849407196045 model params = Parameter containing:
tensor([[1.3198]], requires_grad=True)
Epoch: 20, Loss: 1.1118203401565552 model params = Parameter containing:
tensor([[1.3731]], requires_grad=True)
Epoch: 25, Loss: 1.106642484664917 model params = Parameter containing:
tensor([[1.4189]], requires_grad=True)
Epoch: 30, Loss: 1.1021840572357178 model params = Parameter containing:
tensor([[1.4606]], requires_grad=True)
Epoch: 35, Loss: 1.0983264446258545 model params = Parameter containing:
tensor([[1.4992]], requires_grad=True)
Epoch: 40, Loss: 1.0949875116348267 model params = Parameter containing:
tensor([[1.5350]], requires_grad=T

In [21]:
# evaluation
with torch.no_grad():
  y_pred = model(X_test)
  loss = loss_func(y_pred,y_test)
  print(f"Test Loss: {loss.item()}")

Test Loss: 0.9336553812026978


#### Problem 3
##### Basic Neural Network for Classification:

- Use the MNIST dataset (available through torchvision.datasets) to train a simple neural network for digit classification.
- Build a network with one or two fully connected layers.
- Use torch.nn.CrossEntropyLoss as the loss function and torch.optim.Adam for optimization.
- Train the model and calculate the accuracy on a test set.

In [39]:
# import libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

# check for gpu
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# load mnist dataset
train_dataset = torchvision.datasets.MNIST(root='./data',train=True,transform=transforms.ToTensor(),download=True)
test_dataset = torchvision.datasets.MNIST(root='./data',train=False,transform=transforms.ToTensor(),download=True)

train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True,pin_memory=True)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=False,pin_memory=True)

# model
class NeuralNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(28*28,128)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(128,10)
  def forward(self,X):
    out = X.view(-1,28*28)
    out = self.fc1(out)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.relu(out)
    out = torch.softmax(out,dim=1)
    return out

model = NeuralNet().to(device)

# epochs and lr
epochs = 50
lr = 0.01

# loss and optimiser
loss_func = nn.CrossEntropyLoss()
optimiser = optim.Adam(model.parameters(),lr=lr)

for epoch in range(epochs):
  for train_data,train_labels in train_dataloader:

    # move data to gpu
    train_data,train_labels = train_data.to(device),train_labels.to(device)

    # forward pass
    y_pred = model(train_data)

    # loss calc
    loss = loss_func(y_pred,train_labels)

    # back propagate
    loss.backward()

    # update parameters
    optimiser.step()

    # zero grads
    optimiser.zero_grad()

  print(f"Epoch: {epoch}, Loss: {loss.item()}")

Epoch: 0, Loss: 1.5139317512512207
Epoch: 1, Loss: 1.598649024963379
Epoch: 2, Loss: 1.550708293914795
Epoch: 3, Loss: 1.573744773864746
Epoch: 4, Loss: 1.570813536643982
Epoch: 5, Loss: 1.571285367012024
Epoch: 6, Loss: 1.6025352478027344
Epoch: 7, Loss: 1.6288316249847412
Epoch: 8, Loss: 1.607490062713623
Epoch: 9, Loss: 1.487445592880249
Epoch: 10, Loss: 1.686124563217163
Epoch: 11, Loss: 1.7799012660980225
Epoch: 12, Loss: 1.602535367012024
Epoch: 13, Loss: 1.5762405395507812
Epoch: 14, Loss: 1.6238749027252197
Epoch: 15, Loss: 1.6144678592681885
Epoch: 16, Loss: 1.650169849395752
Epoch: 17, Loss: 1.6272178888320923
Epoch: 18, Loss: 1.6288331747055054
Epoch: 19, Loss: 1.518695592880249
Epoch: 20, Loss: 1.5698338747024536
Epoch: 21, Loss: 1.5712852478027344
Epoch: 22, Loss: 1.6424916982650757
Epoch: 23, Loss: 1.5141994953155518
Epoch: 24, Loss: 1.5712852478027344
Epoch: 25, Loss: 1.611175775527954
Epoch: 26, Loss: 1.5926249027252197
Epoch: 27, Loss: 1.6124457120895386
Epoch: 28, Los

In [40]:
# evaluate MNIST
with torch.no_grad():
  correct = 0
  total = 0
  for test_data,test_labels in test_dataloader:
    # move data to gpu
    test_data,test_labels = test_data.to(device),test_labels.to(device)

    y_pred = model(test_data)
    _,predicted = torch.max(y_pred.data,1)
    total += test_labels.size(0)
    correct += (predicted == test_labels).sum().item()
print(f"Accuracy = {correct/total}")

Accuracy = 0.8673


In [41]:
with torch.no_grad():
  correct = 0
  total = 0
  for train_data,train_labels in train_dataloader:
    # move data to gpu
    train_data,train_labels = train_data.to(device),train_labels.to(device)

    y_pred = model(train_data)
    _,predicted = torch.max(y_pred.data,1)
    total += train_labels.size(0)
    correct += (predicted == train_labels).sum().item()
print(f"Accuracy = {correct/total}")

Accuracy = 0.87035


#### Problem 4
##### Loading and Preprocessing Data:

- Download the CIFAR-10 dataset using torchvision.datasets.
- Apply basic transformations to the images, such as normalization and converting to tensors using torchvision.transforms.
- Create DataLoader instances for training and testing.

#### Problem 5
##### Working with Gradients:

- Create a simple scalar tensor and set requires_grad=True.
- Perform some operations on it.
- Calculate the gradients using backward().
- Inspect the grad attribute of the tensor.

In [8]:
import torch

x = torch.tensor(1200.0, requires_grad = True)
y = 2*x
z = torch.sin(y)
z.backward()
print(x.grad)
def dz_dx():
  return 2*torch.cos(2*x)
print(dz_dx())

tensor(1.9688)
tensor(1.9688, grad_fn=<MulBackward0>)


### Level 2

#### Problem 1
##### Convolutional Neural Network (CNN) for Image Classification:

- Use the CIFAR-10 dataset again.
- Build a CNN with convolutional layers, pooling layers, and fully connected layers.
- Train the CNN and compare its performance to the simple fully connected network from the beginner level.

#### Problem 2
##### Transfer Learning:

- Use a pre-trained ResNet model from torchvision.models.
- Freeze the weights of the pre-trained layers and train only the classification head on a smaller image dataset (e.g., a subset of CIFAR-10 or a custom dataset).

#### Problem 3
##### Modified LeNet Architecture
Your LeNet architecture must incorporate the following changes:
- Include a softmax layer at the end.
- Use x*sigmoid(x) as the activation function.
- Replace average pooling with max pooling.
- Use only 3×3 filters in convolutional layers.

Note:
- Input Size: 32x32 pixels.
- C1(6),S2(6),C3(16),S4(16),C5(120),S6(84),output(10)


#### Problem 4
##### Object Detection (using a pre-trained model):

- Explore how to use a pre-trained object detection model from libraries like torchvision.models.detection (e.g., Faster R-CNN, YOLO).
- Try to run inference on some images. (Training from scratch can be computationally intensive).