<a href="https://colab.research.google.com/github/VinayChavan2006/EE655-Computer-Vision-and-Deep-Learning/blob/main/Pytorch_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch Problems

### Level 1

#### Problem 1
##### Tensor Basics:

- Create a random tensor of size (5, 3).
- Perform element-wise addition, subtraction, multiplication, and division between two tensors of the same size.
- Calculate the mean and standard deviation of a tensor.
- Reshape a tensor from (4, 4) to (16,) and then back to (2, 8).
- Convert a NumPy array to a PyTorch tensor and vice versa.

In [3]:
import torch
import numpy as np

# create random tensor of size (5,3)
tensor1 = torch.rand(5,3)
print(tensor1)
print("\n\n")

# some more tensors
t_ones = torch.ones(4,3)
t_zeros = torch.zeros(3,3)
t_range = torch.arange(10,dtype=torch.float32)
t_lin = torch.linspace(1,10,3)

tensors = [t_ones,t_zeros,t_range,t_lin]
for tensor in tensors:
  print(tensor)
  print(tensor.dtype,tensor.shape,tensor.dim)
  print("\n\n")

# Element wise operations
t1 = torch.randint(0,20,(3,4))
t2 = torch.randint(0,25,(3,4))

print(t1)
print(t2)
print(t1+t2)
print("\n\n")
print(t1 - t2)
print("\n\n")
print(t1 * t2)
print("\n\n")
print(torch.div(t1,t2))

# mean and std of a tensor
ten1 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print("mean",ten1.mean())
print("median: ",ten1.median())
print("std: ",ten1.std())


# reshape_tensor
re_ten = torch.randint(0,10,(4,4))
print(re_ten)
print(re_ten.view(16))
print(re_ten.view(-1,8))

# covert a numpy array in to torch tensor and vice versa
np_arr = np.array([[100,200,300],[120,240,360],[200,300,400]])
np_tens = torch.Tensor(np_arr)
print(np_tens)

tens_arr = torch.randn(3,3)
tens_np = np.array(tens_arr)
print(tens_np)


tensor([[0.7125, 0.3412, 0.9735],
        [0.2806, 0.7881, 0.4378],
        [0.0670, 0.9736, 0.7880],
        [0.8294, 0.4619, 0.3291],
        [0.4015, 0.0828, 0.9700]])



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32 torch.Size([4, 3]) <built-in method dim of Tensor object at 0x7dddadcebef0>



tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32 torch.Size([3, 3]) <built-in method dim of Tensor object at 0x7dddadceb290>



tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32 torch.Size([10]) <built-in method dim of Tensor object at 0x7dddadceb2f0>



tensor([ 1.0000,  5.5000, 10.0000])
torch.float32 torch.Size([3]) <built-in method dim of Tensor object at 0x7dddadcebcb0>



tensor([[ 8, 15,  0, 18],
        [18, 15,  8,  5],
        [17,  0, 19,  7]])
tensor([[19, 22,  4,  5],
        [24, 15, 10, 18],
        [22, 17, 15,  4]])
tensor([[27, 37,  4, 23],
        [42, 30, 18, 23],
        

#### Problem 2
##### Simple Linear Regression:
-
Implement linear regression from scratch using PyTorch. Generate some synthetic data (e.g., y = 2x + 1 + noise).
- Define a simple linear model with one input and one output.
- Use torch.nn.MSELoss as the loss function and torch.optim.SGD for optimization.
- Train the model for a few epochs and observe the loss decreasing.

#### Problem 3
##### Basic Neural Network for Classification:

- Use the MNIST dataset (available through torchvision.datasets) to train a simple neural network for digit classification.
- Build a network with one or two fully connected layers.
- Use torch.nn.CrossEntropyLoss as the loss function and torch.optim.Adam for optimization.
- Train the model and calculate the accuracy on a test set.

#### Problem 4
##### Loading and Preprocessing Data:

- Download the CIFAR-10 dataset using torchvision.datasets.
- Apply basic transformations to the images, such as normalization and converting to tensors using torchvision.transforms.
- Create DataLoader instances for training and testing.

#### Problem 5
##### Working with Gradients:

- Create a simple scalar tensor and set requires_grad=True.
- Perform some operations on it.
- Calculate the gradients using backward().
- Inspect the grad attribute of the tensor.

### Level 2

#### Problem 1
##### Convolutional Neural Network (CNN) for Image Classification:

- Use the CIFAR-10 dataset again.
- Build a CNN with convolutional layers, pooling layers, and fully connected layers.
- Train the CNN and compare its performance to the simple fully connected network from the beginner level.

#### Problem 2
##### Transfer Learning:

- Use a pre-trained ResNet model from torchvision.models.
- Freeze the weights of the pre-trained layers and train only the classification head on a smaller image dataset (e.g., a subset of CIFAR-10 or a custom dataset).

#### Problem 3
##### Modified LeNet Architecture
Your LeNet architecture must incorporate the following changes:
- Include a softmax layer at the end.
- Use x*sigmoid(x) as the activation function.
- Replace average pooling with max pooling.
- Use only 3×3 filters in convolutional layers.

Note:
- Input Size: 32x32 pixels.
- C1(6),S2(6),C3(16),S4(16),C5(120),S6(84),output(10)


#### Problem 4
##### Object Detection (using a pre-trained model):

- Explore how to use a pre-trained object detection model from libraries like torchvision.models.detection (e.g., Faster R-CNN, YOLO).
- Try to run inference on some images. (Training from scratch can be computationally intensive).